In [1]:
from nwtrace import *
import pandas as pd
import geopandas as gpd

In [2]:
segments = gpd.read_file('data/more/full_sewers.geojson')
nodes = gpd.read_file('data/more/all_manholes.geojson')

original_segments = segments.copy()

s_id = "FACILITYID"
n_id = "FACILITYID"
ups = "FROMMH"
dwns = "TOMH"

In [3]:
nodes = nodes.rename(columns={n_id: 'node_id'})
n_id = 'node_id'

In [5]:
repaired_segments = repair.repair_segment_connections(
    segments,
    nodes,
    s_id,
    n_id,
    ups,
    dwns,
    distance_threshold=0.1
)

In [6]:
reference_segment = "SL0000-014-2471"

In [7]:
original_segments[original_segments[s_id] == reference_segment][[s_id, ups, dwns]]

            FACILITYID        FROMMH          TOMH
18219  SL0000-014-2471  MH5125721065  MH5121821078

In [8]:
repaired_segments[repaired_segments[s_id] == reference_segment][[s_id, ups, dwns]]

                      FACILITYID        FROMMH            TOMH
FACILITYID
SL0000-014-2471  SL0000-014-2471  MH5125721065  MH5121821078-1